// Copyright Contributors to the Open Shading Language project.
// SPDX-License-Identifier: BSD-3-Clause
// https://github.com/AcademySoftwareFoundation/OpenShadingLanguage

shader hart_material_channels(point position = point(0),
                              output color value = 0, output float alpha = 0)
{
    float data = texture("hart_texture_alpha_4.exr", position[0], position[1],
                         "interp", "linear", "wrap", "clamp",
                         "firstchannel", 2, "alpha", alpha);
    value = texture("hart_texture_alpha_4.exr", position[0], position[1],
                    "interp", "linear", "wrap", "clamp", "firstchannel", 1)
            + color(0.125 * data);
}
