// Copyright Contributors to the Open Shading Language project.
// SPDX-License-Identifier: BSD-3-Clause
// https://github.com/AcademySoftwareFoundation/OpenShadingLanguage

shader hart_aggregate_indices(int kind = 0, int offset = 0,
                              output color Cout = 0)
{
    float q = 0;
    if (kind == 0) {
        vector a = vector(u, v, u*v);
        int index = int(2*u) + offset;
        a[index] += u;
        q = a[index];
    } else if (kind == 1) {
        matrix a = matrix(1);
        int row = int(3*u) + offset;
        int column = int(3*v);
        a[row][column] = 2*u+v;
        q = a[row][column];
    } else if (kind == 2) {
        int a[3] = {3,5,7};
        int copy[3];
        copy = a;
        int index = int(2*u) + offset;
        copy[index] += int(4*v);
        q = copy[index];
    } else {
        matrix a[2] = {matrix(u),matrix(v)};
        matrix copy[2];
        copy = a;
        int index = int(u >= 0.5) + offset;
        copy[index] = matrix(2*u+v);
        q = copy[index][0][0];
    }
    Cout = color(q, Dx(q), Dy(q));
}
